spring:
  datasource:
    url: jdbc:postgresql://dpg-ct8pdot2ng1s739os3h0-a.frankfurt-postgres.render.com/carto
    username: carto_user
    password: TgkGfBeZDaNqF31zQnWhIUZn87nCWEEJ
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver